### ISSUE TITLE
enable pkg.pacman.store IPNS updates over pub-sub

### ISSUE THREAD

**Issue by guysv** [RubenKelevra/pacman.store#12]
IPNS has an experimental feature to publish name updates over pub-sub. [[link](https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md#ipns-pubsub)]
This allows cluster subscribers to get "push notifications" for cluster updates.

From a few ad-hoc observations I made on my own, resolving "pkg.pacman.store" is the main bottleneck when downloading packages from the cluster, and sometimes can reach even 40 seconds(!).

IPNS over pubsub could reduce the time needed to resolve "pkg.pacman.store" but it requires cooperation from the name holder.

Please consider enabling this feature on the master node, and update the documentation to hint this feature is available.

**Comment by RubenKelevra** [comment]
Hey!


thanks for the recommendation, but actually this feature should already be turned on:

My service file looks like this:

```
$ systemctl status ipfs@ipfs
● ipfs@ipfs.service - InterPlanetary File System (IPFS) daemon
     Loaded: loaded (/usr/lib/systemd/system/ipfs@.service; enabled; vendor preset: disabled)
    Drop-In: /etc/systemd/system/ipfs@.service.d
             └─override.conf
     Active: active (running) since Fri 2020-01-31 20:44:49 CET; 6 days ago
   Main PID: 592 (ipfs)
      Tasks: 90 (limit: 19181)
     Memory: 4.6G
     CGroup: /system.slice/system-ipfs.slice/ipfs@ipfs.service
             └─592 /usr/bin/ipfs daemon --enable-pubsub-experiment --enable-namesys-pubsub --enable-mplex-experiment
```

The config file setting for pubsub is the following:

```
  "Pubsub": {
    "DisableSigning": false,
    "Router": "gossipsub",
    "StrictSignatureVerification": false
  },
```
I also raised high and low water for the connections to 1500 and 1400 for the server, to increase the chance for a good connection to the clients and allow many clients to pin from the server at the same time.

Is something missing?

**Comment by guysv** [comment]
well, according to the documentation, you need to
> run your daemon with the --enable-namesys-pubsub flag; enables pubsub.

But thats for a plain go-ipfs node, no idea how to configure that for a cluster node.

**Comment by RubenKelevra** [comment]
@guysv the cluster doesn't matter here. I run an IPFS daemon which publishes a IPNS for a CID of an MFS folder.

Just the whole pinning management runs thru the cluster, but that's not affecting the IPNS lookup.

I'm wondering if it might be something else, can you run the three steps seperate on your node to get a folder listing:

`time ipfs resolve -r /ipns/pkg.pacman.store/`

`time ipfs dht findprovs -n 1 /ipfs/<CID>`


`time ipfs pin add --recursive=false --progress /ipfs/<CID>`  


This would be very helpful to identify the bottleneck! :)

**Comment by guysv** [comment]
well, I fired up the pubsub switches myself now, and `time ipfs resolve -r /ipns/pkg.pacman.store/` takes about 10 seconds. the weird thing is that `time ipfs dht findprovs -n 1 /ipfs/<CID>` returnes none.. even though actually doing `ipfs ls /ipns/pkg.pacman.store` does return the dir index.

also, `ipfs pin ls | grep <CID>` returned none, at least until I ran `ipfs pin add --recursive=false --progress /ipfs/<CID>`

**Comment by RubenKelevra** [comment]
> well, I fired up the pubsub switches myself now, and `time ipfs resolve -r /ipns/pkg.pacman.store/` takes about 10 seconds.

10 seconds sounds reasonable. Keep in mind that the CID behind the IPNS is changing quite often (on every db/package update) and therefore the cache timeout is set somewhat low.

I saw numbers of 2 to 20 seconds in my tests, which sounds reasonable for me. It's more important that the resolution is successful 100% of the time

> the weird thing is that `time ipfs dht findprovs -n 1 /ipfs/<CID>` returnes none.. even though actually doing `ipfs ls /ipns/pkg.pacman.store` does return the dir index.

That's extremely weird. I currently don't pin the directory in the cluster, because I just forgot to add this to my script, but I'm checking the availability on the ipfs.io gateway with an external service. So at least the gateways should hold a copy of the directory listing.

I'm wondering if there's noone returned since the nodes currently either hold the directory listing OR the data, but not both. 🤔

Definitely worth investigating.

> also, `ipfs pin ls | grep <CID>` returned none, at least until I ran `ipfs pin add --recursive=false --progress /ipfs/<CID>`

That's to be expected. Regardless if you run this on a cluster follower node or a regular one, you need to pin it before you can find it in the pinned list. (As I stated above, the follower nodes currently don't pin the directory itself).

I'll rework the sync script to be able to offer a prefetch daemon for clients, which will automatically pin new updates, which means pacman doesn't have to wait for the packages to be downloaded when you run a update process.

**Comment by RubenKelevra** [comment]
@guysv please test again, I reworked the scripts to speed up the directory listing. :)

First wget on a http-gateway for a directory takes now around 2 seconds:

```
time wget https://ipfs.io/ipns/pkg.pacman.store/
real    0m1,990s
time wget https://cloudflare-ipfs.com/ipns/pkg.pacman.store/
real    0m0,676s
```

**Comment by guysv** [comment]
yes, my experience has improved. thank you!

**Comment by RubenKelevra** [comment]
Great! Can this be closed or do you see still room for improvements?

**Comment by RubenKelevra** [comment]
> well, I fired up the pubsub switches myself now, and `time ipfs resolve -r /ipns/pkg.pacman.store/` takes about 10 seconds. the weird thing is that `time ipfs dht findprovs -n 1 /ipfs/<CID>` returnes none.. even though actually doing `ipfs ls /ipns/pkg.pacman.store` does return the dir index.
> 
> also, `ipfs pin ls | grep <CID>` returned none, at least until I ran `ipfs pin add --recursive=false --progress /ipfs/<CID>`

This bug has been reported to go-ipfs:

https://github.com/ipfs/go-ipfs/issues/6917#issue-568829540
