### ISSUE TITLE
Split the cluster into multiple interest groups

### ISSUE THREAD

**Issue by guysv** [RubenKelevra/pacman.store#14]
The 100GB space requirement is pretty hard to justify.

The reason I'm on this boat, is because I believe having arch packages on IPFS can really compete with traditional package mirrors in upgrade performance and decentralization (duh!).

Because of that, what I expect from this project to provide is just the newest packages, nothing else. Looking at [Arch's stats](https://www.archlinux.org/visualize/), that shouldn't cross the 40GB line.

I understand why one would like to create an entire archive dedicated to archlinux on IPFS, providing old packages and ISOs, but those files are not really needed to my daily needs, and don't meet the reason of why I'm here in the first place.

Therefore, I would like you to split the cluster into multiple interest groups, separating people like myself, who are only interested in the cluster as a source for the newest packages, from people who want to chip into the historical archiving effort.

Final words: If I really miss the target with my requests, I would prefer to fork into a new cluster I will manage as I see fit, rather then chasing this cluster's tail to do what I want.

**Comment by RubenKelevra** [comment]
Hey @guysv,

I really appreciate your input! I'm sorry if you haven't found the right tone in the discussion, English isn't a native language for me. I was going ahead picking up all ideas from both threads and implementing what made the most sense to me.

The point of creating an 2 month archive in the first place was more of an "we can get this basically for free, since it won't create new traffic on the cluster". And it allows for very easy downgrades, which are not possible if you don't hold a local cache of the package files on your machines anymore, in favour of an IPFS cache.

Since the machines most likely have still the old version in their cache, you basically just need an listing of the CIDs to get the filename for the file you're searching.

Using IPFS creates some overhead, a full import is currently at around 43 GB. Since I have no idea what exactly the delta per month is going to be, I was pretty conservative for picking a number off my head.

The 100 GB space requirement was more a recommendation to avoid constant garbage collection runs on cluster members.

I see your point that splitting the archive from a daily mirror makes sense in the future. So you just like to follow the current mirror pkg.pacman.store but not hold the 2 month old versions.

That's actually a good idea I will implement that.

Best regards

Ruben

**Comment by RubenKelevra** [comment]
@guysv how long would you consider a reasonable amount of time, after a package disappeared from the mirror after you wouldn't consider it's necessary to keep it any longer for "downgrade one version" functionality?

I just picked 2 month, since the server has enough space anyway and this value can be changed on the fly whileever we want. But it might be a bit excessive.

**Comment by RubenKelevra** [comment]
I've dug a bit thru the current development around IPNS pinning. This is essentially what you're requesting. You can just pin the IPNS pkg.pacman.store in your client and just all updates precached, while not holding any old packages pinned.

In contrast to the work required to run multiple clusters, this looks like a better approach.

https://github.com/ipfs-shipyard/cohosting/pull/2

**Comment by RubenKelevra** [comment]
Until the following of IPNS records is officially possible with a UI or the CLI, you can use this script:

https://github.com/RubenKelevra/pacman.store/blob/master/toolset/follow_cluster_parts.sh

It will query the DNSLink/IPNS and the repo folder if there are updates. If there are updates it will pin the new one and unpin the old version of the pkg folder afterwards.

Just run it with cron/systemd timer as the system user which also runs your ipfs as often as you like.

Note that the repo size for IPFS needs to have some GB of headroom, to make the update possible, so the usual ~44 GB of the repo plus some headroom needs to be configured. 

The first time you run the script, you need to provide the argument '--firstrun'.

If you like to cache the iso files as well, just run a second instance and change the line 32 accordingly to `iso.pacman.store`.
