### ISSUE TITLE
Network Negotiation Too Slow

### ISSUE THREAD

**Issue by LogoiLab** [RubenKelevra/pacman.store#17]
With a normal setup and an average of 850 peers negotiation via a local gateway is too slow for pacman. It times out with `transfer was less than 1b/s for more than 10 seconds`. I got around this for the db files by pinning them. I cannot do this for the entire repo. What is the point of this if pacman just defaults to a different mirror because the negotiation is too slow.

**Comment by RubenKelevra** [comment]
@LogoiLab thanks for the report. That's why I prefer a setup where the cache subfolder is locally mounted, and can be accessed by pacman as cache.

I hit some performance issues and bugs with this setup, so did go ahead and changed the IPFS-Folders to be compatible with a regular.

I plan to release this method soon.

---

You can work around this 'bug' by setting the ` --disable-download-timeout` flag for pacman.

Note that this might lead to indefinitely hangs, if for example the IPFS-Daemon looses internet connection.

**Comment by mohe2015** [comment]
`ipfs daemon --enable-pubsub-experiment --enable-namesys-pubsub` may also help as it improves repeated name resolutions.

**Comment by RubenKelevra** [comment]
@mohe2015 actually not repeated name resolutions, since the name resolutions are cached up to the ttl time (5 minutes for my records) in the client - but it will speed up the name resolution in general.

I get name resolution times around 1-3 seconds here, from a freshly started node:

```
time ipfs resolve /ipns/pkg.pacman.store
/ipfs/QmNNwg8rhFhCmDRTobdy2hf4HgTaktGacNUomRrMrg711E

real    0m2,467s
user    0m0,016s
sys     0m0,031s
```

Since this "resolution" changes every time there's any change in the packages it's clear that this cannot be cached more than the currently configured 5 minutes.

---

The main delay comes from the fact, that the size of a file is stored in the first block, so before the local HTTP gateway can return a '200' code, it needs to fetch 256 KByte and parse the data to get the size of the file you're want to download.

To download this data it needs to fetch the directory listings first, to get the CID of the file you're requesting.

**Comment by RubenKelevra** [comment]
I've added the information to the readme file:

https://github.com/RubenKelevra/pacman.store/commit/96cf8a61cd58acf8ca8c407d6980dddc419266ac

**Comment by LogoiLab** [comment]
I'll give this stuff a try. Thanks.

**Comment by RubenKelevra** [comment]
@LogoiLab also note that this isn't going to stay this way, the issue (slow directory lookups) and sometimes slow DHT-requests is currently worked on by the developers.

DHT-request improvements are probably landing in the next version, while a rework of the filesystem structure in IPFS is going to take a bit longer.

I tweaked my settings on the server a bit, maybe it's squeezing out a bit more performance. :)

**Comment by RubenKelevra** [comment]
@LogoiLab How is the performance in the last days? I've updated to the 0.5.0rc1 version on one of the servers :)

**Comment by mohe2015** [comment]
Just as you say that I think it actually got better. (But also wait for LogoiLab's response)

**Comment by RubenKelevra** [comment]
@mohe2015 @LogoiLab 

I've updated to 0.5.0-rc3 and found a bug which meant that some files wouldn't be hold in the cluster - just on one node.

It's working alright for me now (comparable to a HTTP mirror)

**Comment by LogoiLab** [comment]
Speed has indeed improved. It really is just a limitation of the protocol itself, until more work is done on the IPFS side of things this will always be an issue for latency dependent projects.

**Comment by RubenKelevra** [comment]
> Speed has indeed improved. It really is just a limitation of the protocol itself, until more work is done on the IPFS side of things this will always be an issue for latency dependent projects.

There's a lot of work going on on the IPFS side. My servers for example support QUIC, which should reduce the latency for connection time, when you enable it.

Using IPFS has the advantage, that all downloads use the same connection - so no new connection has to be established for every new download. :)

**Comment by RubenKelevra** [comment]
@LogoiLab take a look at the FAQ:

https://github.com/RubenKelevra/pacman.store/wiki/FAQ

Could the issue be resolved by it?

**Comment by sinkuu** [comment]
Instead of specifying `--disable-download-timeout` option everytime, it can be persisted by adding `DisableDownloadTimeout` to `[options]` section of `/etc/pacman.conf`.

Off-topic (as the bottleneck seems to be initial DHT queries), but: serially downloading each file does not make sense with IPFS, and it may be better to fill wantlist at once and let IPFS daemon find contents at will. Here's how to use [Powerpill](https://xyne.archlinux.ca/projects/powerpill/):

1. `yay -S powerpill` and `yay --save --pacman powerpill` (if you are using [yay])
2. Add `SigLevel = PackageRequired` to `[options]` section of `/etc/pacman.conf` (as per [Powerpill#Troubleshooting](https://wiki.archlinux.org/index.php/Powerpill#Troubleshooting))
3. Add `--async-dns=false` to `aria2.args` array of `/etc/powerpill/powerpill.json` (this seems to be required for resolving `*.ipns.localhost` domain)

[yay]: https://github.com/Jguer/yay

**Comment by RubenKelevra** [comment]
> Instead of specifying `--disable-download-timeout` option everytime, it can be persisted by adding `DisableDownloadTimeout` to `[options]` section of `/etc/pacman.conf`.

I would avoid setting this option. When you do any kind of scripting, your script might hang indefinitely.

It's better to just add the remote multiple times to the mirrorlist. In daily usage the second time the requests get fullfilled 100% of the time. 

> Off-topic (as the bottleneck seems to be initial DHT queries)

The DHT won't be used for the requests, since the peers should be in the peerstore and the latest IPNS should be received by pubsub.

but: serially downloading each file does not make sense with IPFS, and it may be better to fill wantlist at once and let IPFS daemon find contents at will. Here's how to use [Powerpill](https://xyne.archlinux.ca/projects/powerpill/):
> 
> 1. `yay -S powerpill` and `yay --save --pacman powerpill` (if you are using [yay](https://github.com/Jguer/yay))
> 2. Add `SigLevel = PackageRequired` to `[options]` section of `/etc/pacman.conf` (as per [Powerpill#Troubleshooting](https://wiki.archlinux.org/index.php/Powerpill#Troubleshooting))
> 3. Add `--async-dns=false` to `aria2.args` array of `/etc/powerpill/powerpill.json` (this seems to be required for resolving `*.ipns.localhost` domain)

This is completely unnecessary and pretty hacky IMHO, since IPFS just needs one roundtrip to fetch the next file, it's much faster than HTTPS downloads.

The next version of pacman will use parallel downloads by default.

@sinkuu would you mind opening a new issue, if there's a problem receiving updates via IPFS in a timely manner?

**Comment by sinkuu** [comment]
> The DHT won't be used for the requests, since the peers should be in the peerstore and the latest IPNS should be received by pubsub.

IPNS resolution is fast. However `yay -Syu` stalls at `0%` for a while before actually starting downloading, and `ipfs bitswap wantlist` seems to indicate that the daemon is looking for `/arch/x86_64/default/db` part. Stalling in this phase means it's querying DHT and reaching for peers that have these directories, I think.

> This is completely unnecessary and pretty hacky IMHO, since IPFS just needs one roundtrip to fetch the next file, it's much faster than HTTPS downloads.

Oh, to me, it's a lot slower than HTTP mirror, and powerpill is helping a bit ...on average.

|Mirror| `pacman/powerpill -Sy` Time (sec.)|
|-|-|
| HTTP | 3.80 |
| HTTP + powerpill | 8.39 |
| IPFS | 46.75, 117.30, 90.38 (3 trials) |
| IPFS + powerpill | 24.12, 44.76, 55.24 |

(ran `rm /var/lib/pacman/sync/*.db` and `ipfs repo gc` as needed)
Are these numbers look strange? If so, I'll open a issue.

**Comment by RubenKelevra** [comment]
Well, seeing the request for the db subfolder is quite unexpected. The dbs _are_ stored there but pacman requests the copies from the individual repositories and should just ignore the db folder at all.

I guess the db folder will just be downloaded because it's in the `default` folder.

Currently, the directories are only held by nodes that already downloaded the update and the import server - not the cluster itself.

With the last version of ipfs-cluster, it wasn't possible to just pin folders without their content (recursively added as well). I will add this in the next days which should speed up the directory downloads.

That's my numbers:

IPFS
```
[root@i3 ruben]# time pacman -Syy
:: Synchronizing package databases...
 core                                                                               134,2 KiB  43,7 MiB/s 00:00 [###################################################################] 100%
 extra                                                                             1713,3 KiB  4,74 MiB/s 00:00 [###################################################################] 100%
 community                                                                            4,9 MiB   636 KiB/s 00:08 [###################################################################] 100%
 multilib                                                                           161,8 KiB  0,00   B/s 00:00 [###################################################################] 100%

real	0m12,823s
user	0m0,014s
sys	0m0,022s
```

HTTPS
```
[root@i3 ruben]# time pacman -Syy
:: Synchronizing package databases...
 core                                                                               134,2 KiB  1119 KiB/s 00:00 [###################################################################] 100%
 extra                                                                             1713,3 KiB  1673 KiB/s 00:01 [###################################################################] 100%
 community                                                                            4,9 MiB  2,31 MiB/s 00:02 [###################################################################] 100%
 multilib                                                                           161,8 KiB  2,77 MiB/s 00:00 [###################################################################] 100%

real	0m3,740s
user	0m0,018s
sys	0m0,081s
```

I see what you mean, but I don't know where the delay comes from. 🤔

**Comment by sinkuu** [comment]
> Well, seeing the request for the db subfolder is quite unexpected. The dbs are stored there but pacman requests the copies from the individual repositories and should just ignore the db folder at all.

Ah, sorry, I heven't actually checked CID shown in `bitswap wantlist` points to `db` directory. It seemed like a parent directory of database (because downloading stalls), and I just guessed that.

**Comment by RubenKelevra** [comment]
The db database is to be able to download just all databases as one CID, without having to load all large directories with all the packages.

So it's there for custom update scripts or manual downloads.

It doesn't consume additional space since it's just a ref-copy.

**Comment by sinkuu** [comment]
```
64 bytes from loki.pacman.store (2a03:4000:34:5c2::f3): icmp_seq=1 ttl=48 time=286 ms
```

**Comment by RubenKelevra** [comment]
> ```
> 64 bytes from loki.pacman.store (2a03:4000:34:5c2::f3): icmp_seq=1 ttl=48 time=286 ms
> ```

Yeah. This explains why it takes so long for you - roundtrip is like 17x faster for me.

This situation will improve as soon as all cluster members will hold the folders since IPFS will be able to fetch it from a cluster member closer to you.

Since IPFS already found the folder on loki, it's likely that the whole download is happening from loki, since bit swap will try to use established connections instead of creating new ones.

So overall download speed should improve as well.

I'll report back when the folders are pinned in the cluster as well.

**Comment by RubenKelevra** [comment]
I think I found the "bug". Everyone test again, please! :)

Nothing has yet changed on the cluster-pins, so the folders will still be fetched from one server, BUT is should be much faster. I see no timeout anymore.

Enhancement request to make this workaround standard: https://github.com/ipfs/go-ipfs/issues/7487

**Comment by RubenKelevra** [comment]
IPFS 0.6:

```
# time pacman -Syy
:: Synchronizing package databases...
 core                                                                               134,4 KiB  32,8 MiB/s 00:00 [###################################################################] 100%
 extra                                                                             1709,8 KiB  3,11 MiB/s 00:01 [###################################################################] 100%
 community                                                                            5,0 MiB  2,45 MiB/s 00:02 [###################################################################] 100%
 multilib                                                                           162,7 KiB   159 MiB/s 00:00 [###################################################################] 100%

real	0m9,779s
user	0m0,011s
sys	0m0,030s

```

HTTPS:

```
# time pacman -Syy
:: Synchronizing package databases...
 core                                                                               134,4 KiB   521 KiB/s 00:00 [###################################################################] 100%
 extra                                                                             1709,8 KiB  1197 KiB/s 00:01 [###################################################################] 100%
 community                                                                            5,0 MiB  2,91 MiB/s 00:02 [###################################################################] 100%
 multilib                                                                           162,7 KiB  3,61 MiB/s 00:00 [###################################################################] 100%

real	0m9,152s
user	0m0,047s
sys	0m0,127s
```

I think we're slowly getting there. :)

**Comment by RubenKelevra** [comment]
Alright, the cluster will hold the folders in the new installation, which did go live today.

You need to update the URL and if you're following the cluster, you need to start a new instance of the cluster follower. Details on the announcement section of the wiki and in the readme.
