### ISSUE TITLE
Bring the archive to IPFS (was:Better format for package archive)

### ISSUE THREAD

**Issue by mohe2015** [RubenKelevra/pacman.store#18]
Hi, I was looking for go-pie 1.13.8 on this cluster but it is really hard to navigate http://old.pkg.pacman.store.ipns.localhost:8080/arch/x86_64/default.old.html. It seems like there are just old pinned versions of the whole repository. Maybe you could get some inspiration from the format of https://archive.archlinux.org/packages/. But I assume that you already thought about that but it is not so easy to implement. It also seems that this clusters archive doesn't go that far into the past (which is fine).

**Comment by RubenKelevra** [comment]
I actually thought about fetching the whole archive as URLs with --nocopy from the archive server with a dedicated node which then just provides a (slow) backup source for fetching older versions. The HTTP requests to the server would be limited to a very slow pace, to avoid that people start fetching huge amounts of data from the server - and I would add a reverse caching proxy in front. But this would require an enormous amount of traffic for the initial chunking - this requires that the server admin(s) agree on that.

Since I have to talk to the admins for this anyway, an IPFS node on the server itself directly accessing the stored files would make much more sense - while fetching outsourced files to archive.org via the known URL.

I currently completely disabled that the cluster will hold older data since it consumed much more storage than expected (more than 100 GB for 1 month).

I don't want that anybody who wants to follow the cluster needs to store old packages - because of the size of the repo.

**Comment by mohe2015** [comment]
I don't think it's worth it do download more packages as I just got it from the official website and it's really rare you need an old package. I just liked there format way more so maybe an rsync of packages not older than n days may be useful. (Or some other heuristic)

**Comment by RubenKelevra** [comment]
> I also saw your efforts on integrating ipfs into the official package format which I think is an awesome idea.

Maybe you can add your opinion to the list? :)



> I don't think it's worth it do download more packages as I just got it from the official website and it's really rare you need an old package. I just liked their format way more so maybe an rsync of packages not older than n days may be useful. (Or some other heuristic)
> 
> Edit: I'm on my phone but maybe you could also reorder the current directory structure automatically so you don't need to download anything at all.

Well, the packages will be available for a long time anyway, since all nodes holding the packages need to run they GC before they will disappear. The more user downloading packages, the more likely it is, that we get a quite long history of packages.

We just need to create folders which hold the packages.

The issue with folders are: When you add a file to a folder, it will remain in the cache.

So we need an independent node that just creates the directories, while it actually holds no data at all - or a node that has enough space to hold the full archive.

I like the second approach better since it allows us to make sure, there's always the last copy available.

If the archive maintainer agrees, it's also possible to have the download's fetched via URL from the archive server, this way there's no storage requirement.

**Comment by mohe2015** [comment]
> > I also saw your efforts on integrating ipfs into the official package format which I think is an awesome idea.
> 
> Maybe you can add your opinion to the list? :)
> 
I'm currently doing my Abitur / A-levels / general qualification for university entrance so I will do that after that so I could look into how pacman works etc.


> > I don't think it's worth it do download more packages as I just got it from the official website and it's really rare you need an old package. I just liked their format way more so maybe an rsync of packages not older than n days may be useful. (Or some other heuristic)
> > Edit: I'm on my phone but maybe you could also reorder the current directory structure automatically so you don't need to download anything at all.
> 
> Well, the packages will be available for a long time anyway, since all nodes holding the packages need to run they GC before they will disappear. The more user downloading packages, the more likely it is, that we get a quite long history of packages.
> 
> We just need to create folders which hold the packages.
> 
> The issue with folders are: When you add a file to a folder, it will remain in the cache.
> 
> So we need an independent node that just creates the directories, while it actually holds no data at all - or a node that has enough space to hold the full archive.
> 
> I like the second approach better since it allows us to make sure, there's always the last copy available.
> 
> If the archive maintainer agrees, it's also possible to have the download's fetched via URL from the archive server, this way there's no storage requirement.

I agree - maybe also a combination if that's worth the effort. So recent files are actually stored and for older files just the hash is stored. I don't know if it's worth using URL fetching as this needs to download everything once to calculate the hash and as you would need to ask the archive maintainer anyways it would probably better to just run ipfs on that server (which may not be agreed to by the archive maintainer when they still agree to fetching the files using the url)

**Comment by RubenKelevra** [comment]
> I agree - maybe also a combination if that's worth the effort. So recent files are actually stored and for older files just the hash is stored. I don't know if it's worth using URL fetching as this needs to download everything once to calculate the hash and as you would need to ask the archive maintainer anyways it would probably better to just run ipfs on that server (which may not be agreed to by the archive maintainer when they still agree to fetching the files using the url)

It would not only fetch all content once from the storage server, it will also fetch the content on every request from the IPFS side.

So if someone decides to pin the whole archive from the IPFS side, the IPFS server would fetch the entire archive from the archive server.

That's why a local server would make more sense, usually, data centers don't meter internal traffic, so everything could be stored on the one archive server and fetched from it, but send with a second server into the IPFS network.

The data could be either accessed via HTTP from the main server or by a network mount.

The main issue with the idea is: Old stuff gets moved to archive.org. I'm not sure how IPFS reacts on http redirects.

**Comment by RubenKelevra** [comment]
Feel free to contact the maintainer and ask for IPFS integration, if you would like to see this. I'm happy to include a redirect to the IPNS of the archive under the pacman.store domain.

**Comment by mohe2015** [comment]
I added it to my TODO after I finished my exams.

**Comment by mohe2015** [comment]
I've decided to switch to another Linux distribution in the near future and therefore I won't be able to work on this. I also don't think that the archive is really worth the effort as I just needed it once in my time with Arch Linux. Integrating ipfs into pacman is an interesting idea. Unfortunately I don't have the time to research how to best integrate them and I think the current approach works quite well and will probably work even better after the directory entries are also stored on all cluster followers.

I wish you and all contributors fun and success with the future of the project.

**Comment by RubenKelevra** [comment]
@mohe2015 thanks for all your feedback, and work on IPFS - and this pacman mirror. 

I think the main idea behind adding the archive would be, that pacman can access older versions via IPFS as easily as the current ones, thus is able to downgrade.

But we see how this goes in the future. :)
